# Generated by Django 4.2.7 on 2023-11-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_excluding_tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tva', models.FloatField(choices=[(5.5, '5.5%'), (20, '20%')])),
                ('ordered_stock', models.PositiveIntegerField()),
                ('max_available_stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
